language: go

go:
  - tip

before_install:
  - sudo apt-get install -y libappindicator-dev build-essential libgtk-3-dev

install:
  - go get -u golang.org/x/vgo
  - go get -u github.com/shurcooL/vfsgen
  - vgo generate

script: vgo build
